name: danchu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0  # Firebase 코어 기능
  firebase_auth: ^4.16.0  # 인증
  cloud_firestore: ^4.17.5  # Firestore 데이터베이스
  firebase_storage: ^11.6.0  # 파일 저장
  firebase_messaging: ^14.7.10  # 푸시 알림
  flutter_colorpicker: ^1.1.0
  flutter_native_splash: ^2.4.1
  http: ^1.2.2
  table_calendar: ^3.1.2
  draggable_home: ^1.0.2
  cupertino_icons: ^1.0.6
  scroll_date_picker: ^3.8.0
  scroll_datetime_picker: ^0.1.2
  intl: ^0.19.0
  flutter_iconpicker: ^3.4.6
  speech_to_text: ^6.6.2
  firebase_database: ^10.5.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/