// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwOxNSSL817oQzTbiTgsvfzEJ6TemQsvM',
    appId: '1:881967360899:web:0abc40bd832ff116d5a4b6',
    messagingSenderId: '881967360899',
    projectId: 'psyched-era-430113-v1',
    authDomain: 'psyched-era-430113-v1.firebaseapp.com',
    databaseURL: 'https://psyched-era-430113-v1-default-rtdb.firebaseio.com',
    storageBucket: 'psyched-era-430113-v1.appspot.com',
    measurementId: 'G-FY7KPTGMBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0eewTTEHQitlirNHcsMevCWmPDDbX8yk',
    appId: '1:881967360899:android:61c777dec0adca3dd5a4b6',
    messagingSenderId: '881967360899',
    projectId: 'psyched-era-430113-v1',
    databaseURL: 'https://psyched-era-430113-v1-default-rtdb.firebaseio.com',
    storageBucket: 'psyched-era-430113-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyqTUdDj7I3O_SRQTsfACfkGssYPIAYZ4',
    appId: '1:881967360899:ios:2894d21fdbca29a5d5a4b6',
    messagingSenderId: '881967360899',
    projectId: 'psyched-era-430113-v1',
    databaseURL: 'https://psyched-era-430113-v1-default-rtdb.firebaseio.com',
    storageBucket: 'psyched-era-430113-v1.appspot.com',
    iosBundleId: 'com.example.danchu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyqTUdDj7I3O_SRQTsfACfkGssYPIAYZ4',
    appId: '1:881967360899:ios:2894d21fdbca29a5d5a4b6',
    messagingSenderId: '881967360899',
    projectId: 'psyched-era-430113-v1',
    databaseURL: 'https://psyched-era-430113-v1-default-rtdb.firebaseio.com',
    storageBucket: 'psyched-era-430113-v1.appspot.com',
    iosBundleId: 'com.example.danchu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwOxNSSL817oQzTbiTgsvfzEJ6TemQsvM',
    appId: '1:881967360899:web:d7eb9b8382b866aed5a4b6',
    messagingSenderId: '881967360899',
    projectId: 'psyched-era-430113-v1',
    authDomain: 'psyched-era-430113-v1.firebaseapp.com',
    databaseURL: 'https://psyched-era-430113-v1-default-rtdb.firebaseio.com',
    storageBucket: 'psyched-era-430113-v1.appspot.com',
    measurementId: 'G-G11L2GTXRL',
  );

}